aws_region       = "us-east-1"
iam_role_name    = "eks-role"
eks_cluster_name = "my-eks-cluster"
eks_cluster_version = "1.27"
nodegroup_role_name = "node-group-role"
nodegroup_name = "my-node-group"